<ul class="list-group">
    <a 
        class="list-group-item" 
        href="inventory.php?sid={{$smarty.get.sid}}" 
        target="ifr-right">
        展示中心庫存查詢
    </a>
    <a 
        class="list-group-item" 
        href="purchase.php?sid={{$smarty.get.sid}}" 
        target="ifr-right">
        展示中心進/退貨記錄表
    </a>
    <a 
        class="list-group-item" 
        href="company_inventory.php?sid={{$smarty.get.sid}}" 
        target="ifr-right">
        公司庫存查詢
    </a>
    <a 
        class="list-group-item" 
        href="company_purchase.php?sid={{$smarty.get.sid}}" 
        target="ifr-right">
        公司進貨記錄表
    </a>
    <a 
        class="list-group-item" 
        href="product.php?sid={{$smarty.get.sid}}" 
        target="ifr-right">
        產品管理
    </a>
    <a 
        class="list-group-item" 
        href="item.php?sid={{$smarty.get.sid}}" 
        target="ifr-right">
        產品類別管理
    </a>
</ul>